# Generated by Django 3.2.20 on 2023-08-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20230828_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='ljorganization',
            name='company',
            field=models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='ljorganization',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name='Phone number'),
        ),
    ]
