# Generated by Django 3.2.20 on 2023-09-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20230828_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='ljorganizationteammember',
            name='status',
            field=models.CharField(choices=[('0', 'Invited'), ('1', 'Active'), ('2', 'Inactive')], default='1', max_length=255, verbose_name='Status'),
        ),
    ]
