# Generated by Django 3.2.20 on 2023-09-01 12:50

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    LJOrganizationTeamMember = apps.get_model('authentication', 'LJOrganizationTeamMember')
    for team_member in LJOrganizationTeamMember.objects.all():
        team_member.uuid = uuid.uuid4()
        team_member.save()


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0004_ljorganizationteammember_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ljorganizationteammember',
            name='uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='Unique UUID hash'),
        ),
        migrations.RunPython(create_uuid, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='ljorganizationteammember',
            name='uuid',
            field=models.UUIDField(unique=True, editable=False)
        )
    ]
