# Generated by Django 3.2.22 on 2023-11-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_ljorganizationteammember_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ljorganizationteammember',
            name='is_customer_facing',
            field=models.BooleanField(default=False, help_text='User who can login to organization incognito', verbose_name='Customer facing user'),
        ),
    ]
