# Generated by Django 3.2.22 on 2023-11-28 15:58

from django.db import migrations, models
import lj_common_shared_service.utils.file


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_ljorganizationteammember_is_customer_facing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ljorganization',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=lj_common_shared_service.utils.file.LJRandomFileName(''), verbose_name='Logo'),
        ),
    ]
