# Generated by Django 2.1.3 on 2020-11-25 10:41

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import embed_video.fields
import lj_common_shared_service.utils.file
import lj_common_shared_service.utils.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LJApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('version', models.IntegerField(blank=True, default=None, null=True, verbose_name='Version')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to=lj_common_shared_service.utils.file.LJRandomFileName(''), verbose_name='Preview photo')),
                ('access_right', models.CharField(choices=[('0', 'Public'), ('1', 'Private'), ('2', 'Organization')], default='0', max_length=255, verbose_name='Access right')),
                ('status', models.CharField(choices=[('0', 'Draft'), ('1', 'Published')], default='0', max_length=255, verbose_name='Status')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date updated')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Favorite')),
                ('is_promoted', models.BooleanField(default=False, verbose_name='Promoted')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Reviewed by LJ team')),
                ('is_sample', models.BooleanField(default=False, verbose_name='Sample application')),
                ('success_message', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Success message')),
                ('failure_message', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Failure message')),
                ('instruction_message', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Instruction message')),
                ('description', models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Description')),
                ('parameter_settings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('video', embed_video.fields.EmbedVideoField(blank=True, default=None, null=True, verbose_name='Video preview')),
                ('webhook_url', models.URLField(blank=True, default=None, null=True, verbose_name='Webhook URL')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
            bases=(models.Model, lj_common_shared_service.utils.mixins.LJProxyModelMixin),
        ),
        migrations.CreateModel(
            name='LJApplicationTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_tag', to='core.LJApplication')),
            ],
            options={
                'verbose_name': 'Application tag',
                'verbose_name_plural': 'Application tags',
            },
        ),
        migrations.CreateModel(
            name='LJCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to=lj_common_shared_service.utils.file.LJRandomFileName(''), verbose_name='Preview photo')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='LJDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to=lj_common_shared_service.utils.file.LJRandomFileName(''), verbose_name='Preview photo')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
            },
            bases=(models.Model, lj_common_shared_service.utils.mixins.LJProxyModelMixin),
        ),
        migrations.CreateModel(
            name='LJDomainAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('clause', models.CharField(max_length=255, verbose_name='Clause')),
                ('call_on_output', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, null=True, size=None, verbose_name='Call methods on output')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public')),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('constraints', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_domain', to='core.LJDomain')),
            ],
            options={
                'verbose_name': 'Domain action',
                'verbose_name_plural': 'Domain actions',
            },
            bases=(models.Model, lj_common_shared_service.utils.mixins.LJProxyModelMixin),
        ),
        migrations.CreateModel(
            name='LJGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
            },
        ),
        migrations.CreateModel(
            name='LJOntology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Name')),
                ('version', models.IntegerField(blank=True, default=None, null=True, verbose_name='Version')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name': 'Ontology',
                'verbose_name_plural': 'Ontologies',
            },
            bases=(models.Model, lj_common_shared_service.utils.mixins.LJProxyModelMixin),
        ),
        migrations.CreateModel(
            name='LJPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, default=None, max_length=255, verbose_name='Label')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('photo', models.ImageField(default=None, upload_to=lj_common_shared_service.utils.file.LJRandomFileName(''), verbose_name='Image photo')),
                ('minX', models.FloatField(default=0.0, verbose_name='Min X')),
                ('minY', models.FloatField(default=0.0, verbose_name='Min Y')),
                ('maxX', models.FloatField(default=0.0, verbose_name='Max X')),
                ('maxY', models.FloatField(default=0.0, verbose_name='Max Y')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.CreateModel(
            name='LJPhotoReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Name')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('device_type', models.CharField(choices=[('0', 'elp'), ('1', 'iphonex')], default='0', max_length=255, verbose_name='Device type')),
                ('is_result_correct', models.BooleanField(blank=True, null=True, verbose_name='The user verified the result is correct')),
                ('status', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Report status')),
                ('message', models.CharField(blank=True, default=None, max_length=2048, null=True, verbose_name='Report message')),
                ('output', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True, verbose_name='Report output')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('camera_angle_to_surface', models.FloatField(default=0.0, verbose_name='Camera angle to surface')),
                ('camera_distance_to_surface', models.FloatField(default=0.0, verbose_name='Camera distance to surface')),
                ('application', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_report', to='core.LJApplication')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_report', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Photo Report',
                'verbose_name_plural': 'Photo Reports',
            },
        ),
        migrations.CreateModel(
            name='LJPhotoReportDetectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(db_index=True, max_length=255, verbose_name='Host')),
                ('name', models.CharField(max_length=255, verbose_name='Model name')),
                ('port', models.PositiveIntegerField(default=0, verbose_name='Port')),
                ('version', models.PositiveIntegerField(default=0, verbose_name='Version')),
                ('type', models.CharField(db_index=True, max_length=255, verbose_name='Model type')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_model_photo_report', to='core.LJPhotoReport')),
            ],
            options={
                'verbose_name': 'Report detection model',
                'verbose_name_plural': 'Report detection models',
            },
        ),
        migrations.CreateModel(
            name='LJPhotoReportImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to=lj_common_shared_service.utils.file.LJRandomFileName(''), verbose_name='File')),
                ('url', models.URLField(blank=True, default=None, null=True, verbose_name='Reference file URL')),
                ('video_id', models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='The video ID from the different service')),
                ('is_annotated', models.BooleanField(default=False, verbose_name='Annotated file image')),
                ('photo_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_report_image', to='core.LJPhotoReport', verbose_name='Photo report')),
            ],
            options={
                'verbose_name': 'Photo report image',
                'verbose_name_plural': 'Photo report images',
            },
        ),
        migrations.CreateModel(
            name='LJPhotoReportImageObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Material name')),
                ('shape', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Shape name')),
                ('color', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Color name')),
                ('class_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Class name')),
                ('class_id', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Class id')),
                ('instance_id', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Instance id')),
            ],
        ),
        migrations.CreateModel(
            name='LJPhotoReportImageObjectBbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.IntegerField(default=0, verbose_name='Left coordinate')),
                ('top', models.IntegerField(default=0, verbose_name='Top coordinate')),
                ('right', models.IntegerField(default=0, verbose_name='Right coordinate')),
                ('bottom', models.IntegerField(default=0, verbose_name='Bottom coordinate')),
            ],
        ),
        migrations.CreateModel(
            name='LJTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to=lj_common_shared_service.utils.file.LJRandomFileName(''), verbose_name='Template icon')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_template', to=settings.AUTH_USER_MODEL, verbose_name='Template owner')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
            },
            bases=(models.Model, lj_common_shared_service.utils.mixins.LJProxyModelMixin),
        ),
        migrations.CreateModel(
            name='LJUserDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', 'elp'), ('1', 'iphonex')], default='0', max_length=5, verbose_name='Device type')),
                ('uid', models.CharField(max_length=255, verbose_name='Device ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Device name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_device', to=settings.AUTH_USER_MODEL, verbose_name='Device owner')),
            ],
            options={
                'verbose_name': 'User device',
                'verbose_name_plural': 'User devices',
            },
            bases=(models.Model, lj_common_shared_service.utils.mixins.LJProxyModelMixin),
        ),
        migrations.CreateModel(
            name='LJVideoFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Report status')),
                ('message', models.CharField(blank=True, default=None, max_length=2048, null=True, verbose_name='Report message')),
                ('output', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True, verbose_name='Report output')),
                ('time', models.FloatField(default=0.0, help_text='Time in seconds', verbose_name='Frame time')),
            ],
            options={
                'verbose_name': 'Video frame',
                'verbose_name_plural': 'Video frames',
            },
        ),
        migrations.CreateModel(
            name='LJVideoReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Name')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('video', models.FileField(blank=True, default=None, null=True, upload_to=lj_common_shared_service.utils.file.LJRandomFileName(''), verbose_name='Video')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('application', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_video_report', to='core.LJApplication')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_video_report', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video report',
                'verbose_name_plural': 'Video reports',
            },
        ),
        migrations.AddField(
            model_name='ljvideoframe',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_frame', to='core.LJVideoReport'),
        ),
        migrations.AddField(
            model_name='ljphotoreportimageobject',
            name='bbox',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.LJPhotoReportImageObjectBbox'),
        ),
        migrations.AddField(
            model_name='ljphotoreportimageobject',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_report_object_image', to='core.LJPhotoReportImage', verbose_name='Photo report image'),
        ),
        migrations.AddField(
            model_name='ljdomainaction',
            name='template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_template', to='core.LJTemplate'),
        ),
        migrations.AddField(
            model_name='ljdomain',
            name='base_ontology',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_ontology', to='core.LJOntology'),
        ),
        migrations.AddField(
            model_name='ljdomain',
            name='ontology',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ontology_domain', to='core.LJOntology'),
        ),
        migrations.AddField(
            model_name='ljdomain',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_domain', to=settings.AUTH_USER_MODEL, verbose_name='Domain owner'),
        ),
        migrations.AddField(
            model_name='ljapplication',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categories_application', to='core.LJCategory', verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='ljapplication',
            name='domain_action',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_action_application', to='core.LJDomainAction'),
        ),
        migrations.AddField(
            model_name='ljapplication',
            name='goals',
            field=models.ManyToManyField(blank=True, related_name='goals_application', to='core.LJGoal', verbose_name='Goals'),
        ),
        migrations.AddField(
            model_name='ljapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_application', to=settings.AUTH_USER_MODEL, verbose_name='Application owner'),
        ),
    ]
