# Generated by Django 3.2.23 on 2024-05-23 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ljcategory_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LJCategory',
        ),
        migrations.DeleteModel(
            name='LJUserDevice',
        ),
    ]
